spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    #过滤返回前端时为null的数据
    default-property-inclusion: non_null
    data:
      redis:
        repositories:
          enabled: false

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.github.linxiaobaixcg.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
      #自定义填充策略接口实现
      global-config.meta-object-handler: MyMetaObjectHandler
    banner: false

# 配置SQL打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#登录图形验证码有效时间/秒
loginCode:
  expiration: 120

#微信登录
wx:
  appid: wx2e75ec758d5ca8ab
  appsecret: a35b37288b40d47845b4c866188b8ab7
  redirect-uri: http://www.baidu.com

app:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization
