spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    hikari:
      #最大连接数
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      #最小链接池
      minimum-idle: 10
      #连接允许在池中闲置的最长时间
      idle-timeout: 60000
      #池中连接最长生命周期
      max-lifetime: 60000