server:
  port: 9008
spring:
  application:
    name: vw-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.98.237.121/vw?characterEncoding=UTF8
    username: root
    password: LCQmysql183187!
    hikari:
      #最大连接数
      maximum-pool-size: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      #最小链接池
      minimum-idle: 10
      #连接允许在池中闲置的最长时间
      idle-timeout: 60000
      #池中连接最长生命周期
      max-lifetime: 60000