server:
  port: 9010
spring:
  application:
    name: vw-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    vw-qa:
      path: /qa/**
      serviceId: vw-qa
    vw-follow:
      path: /follow/**
      serviceId: vw-follow
swagger:
  enable: false
